name: Smoke‐Test Uptime Monitor (build‐on‐the‐fly)

on:
  workflow_dispatch:

permissions:
  contents: write   # needed to commit & push the log-file
  issues: write     # needed to open an issue when a site is down

jobs:
  run-local:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Bundle action code
        run: npx ncc build src/index.js -o dist

      - name: Run our action
        uses: "./"            # action.yml → dist/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sites: |
            https://httpstat.us/200 
            https://httpstat.us/404
            https://httpstat.us/500
            https://httpstat.us/200?sleep=5000
            https://httpstat.us/200?sleep=16000
          timezone: "Europe/Paris"
          log-file: "uptime-smoke.log"
          commit-message: "🔍 Smoke‐test run"
           